### ISSUE TITLE
Depracated?

### ISSUE THREAD

**Issue by Tim15** [theocodes/vue-brunch#28]
![screenshot-2017-10-1 theocodes vue-brunch 1](https://user-images.githubusercontent.com/11166947/31058948-a401c224-a6ca-11e7-89f0-c78b8f8699ce.png)
Is this brunch plugin depracated? If so, are there replacements?

**Comment by tomquirk** [comment]
Not anymore! See #26 for details.

**Comment by tomquirk** [comment]
actually @theocodes you'll need to remove the `deprecated` tag - you're the only one who can do that

**Comment by theocodes** [comment]
done. :)
