### ISSUE TITLE
Drop the vueify dependency

### ISSUE THREAD

**Issue by nblackburn** [theocodes/vue-brunch#3]
Rewrite the plugin to be free of its dependency on Vueify. This will allow me to fine tune it specifically for Brunch and have full control of the source.

**Comment by nblackburn** [comment]
I am in the process of this now for those interested.

**Comment by DerJacques** [comment]
Glad to hear it. Very much appreciated!

**Comment by StanBright** [comment]
Do you think it will work if we update vueify's version to "^10.x.x"? That way we could use newer versions of vue... maybe :)

**Comment by nblackburn** [comment]
@StanBright This isn't really relevant to this discussion but there is no 10.x
