### ISSUE TITLE
migrate from deprecated vue2-brunch

### ISSUE THREAD

**Issue by alec-c4** [theocodes/vue-brunch#31]
Hi,
could you explain me how to migrate from deprecated vue2-brunch to your vue-brunch? For example - if I use code from [this article](https://baroni.tech/blog/phoenix-brunch-vuejs-part1/) I'd like to use maintained code

**Comment by pierrebeitz** [comment]
do you have any problems when switching from `vue2-brunch` to `vue-brunch`?

it looks as if they almost do the same thing (running stuff through `vuetify`), but `vue-brunch` is additionally capable of extracting css.

**Comment by alec-c4** [comment]
ohhh, I've found - I have forgotten to add

```
    vue: {
      extractCSS: true
    }
```

to brunch-config.js
